# App
spring.application.name=Java-Project-PayGuard

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/payguard_db
spring.datasource.username=Sakthi
spring.datasource.password=Sakthi@13809
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/payguard_audit

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=b02ddeaea50c24239d0a70533562bb538485cd421ff797048461a8aef897b47af51a0b2ae44ccda1dd12801ddf4769f55642b52f1346fba5e0525e5595768d23
jwt.expiration=86400000

# Server
server.port=8080