spring.application.name=PayGuard

# ── MySQL Datasource (Externalized for Production/Docker) ──
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payguard_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Sakthi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sakthi@13809}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── Hibernate & JPA (Flyway controls schema) ──
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── Flyway Migrations ──
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ── MongoDB (Audit Logs) ──
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/payguard_audit}

# ── Redis Configuration ──
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# ── JWT Security Properties ──
jwt.secret=${JWT_SECRET:b02ddeaea50c24239d0a70533562bb538485cd421ff797048461a8aef897b47af51a0b2ae44ccda1dd12801ddf4769f55642b52f1346fba5e0525e5595768d23}
jwt.cookie-name=${JWT_COOKIE_NAME:jwt}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}

# ── PayGuard Business Rules ──
payguard.fraud.single-transfer-limit=5000.0000
payguard.fraud.velocity-limit=3
payguard.fraud.velocity-window-seconds=300
payguard.idempotency.ttl-hours=24

# ── Server Port ──
server.port=8080

# ── Phase 15: Swagger / OpenAPI Config ──
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# ── Phase 18: Actuator & Prometheus Observability Config ──
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=PayGuard

# ── Logging ──
logging.level.com.payguard=DEBUG
logging.level.org.springframework.security=INFO
